# Generated by Django 5.2.5 on 2025-08-28 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_projects_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos')),
                ('your_name', models.CharField(blank=True, max_length=150, null=True)),
                ('your_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube_link', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=200, null=True)),
                ('github_link', models.CharField(blank=True, max_length=200, null=True)),
                ('gmail_link', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin_link', models.CharField(blank=True, max_length=200, null=True)),
                ('your_years_of_experience', models.FloatField(blank=True, null=True)),
                ('your_number_of_satisfied_clients', models.FloatField(blank=True, null=True)),
                ('your_number_of_completed_projects', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
            ],
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'verbose_name_plural': 'Project categories'},
        ),
    ]
