# Generated by Django 5.2.5 on 2025-08-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_basicconfiguration_resume_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicconfiguration',
            old_name='logo',
            new_name='logo_dark',
        ),
        migrations.AddField(
            model_name='basicconfiguration',
            name='logo_light',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
    ]
