# Generated by Django 5.2.5 on 2025-08-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_logo_basicconfiguration_logo_dark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicconfiguration',
            name='your_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_images'),
        ),
    ]
