# Generated by Django 5.2.5 on 2025-08-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_basicconfiguration_your_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicconfiguration',
            name='instagram_link',
        ),
        migrations.AlterField(
            model_name='basicconfiguration',
            name='github_link',
            field=models.CharField(blank=True, help_text='The link must start with "http:// or https://"', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='basicconfiguration',
            name='gmail_link',
            field=models.CharField(blank=True, help_text='The link must start with "http:// or https://"', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='basicconfiguration',
            name='linkedin_link',
            field=models.CharField(blank=True, help_text='The link must start with "http:// or https://"', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='basicconfiguration',
            name='youtube_link',
            field=models.CharField(blank=True, help_text='The link must start with "http:// or https://"', max_length=200, null=True),
        ),
    ]
