# Generated by Django 5.2.5 on 2025-08-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_basicconfiguration_instagram_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicconfiguration',
            name='instagram_link',
            field=models.CharField(blank=True, help_text='The link must start with "http:// or https://"', max_length=200, null=True),
        ),
    ]
