# Generated by Django 5.2.5 on 2025-08-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_basicconfiguration_instagram_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_duration', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=250)),
                ('university_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='HardSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_image', models.ImageField(upload_to='skill_images')),
                ('number_of_projects', models.IntegerField()),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SoftSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('work_duration', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(blank=True, null=True)),
                ('educations', models.ManyToManyField(to='base.education')),
                ('hard_skills', models.ManyToManyField(to='base.hardskill')),
                ('soft_skills', models.ManyToManyField(to='base.softskill')),
                ('work_experiences', models.ManyToManyField(to='base.workexperience')),
            ],
        ),
    ]
