# Generated by Django 5.2.5 on 2025-08-28 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_education_hardskill_softskill_workexperience_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
    ]
