# Generated by Django 5.2.5 on 2025-09-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_about_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_message', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='basicconfiguration',
            old_name='gmail_link',
            new_name='upwork_link',
        ),
    ]
