# Generated by Django 5.2.5 on 2025-09-02 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_award_certificate_course_researchpaper_achievement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='image',
            new_name='course_image',
        ),
    ]
