# Generated by Django 5.2.5 on 2025-09-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_image_course_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='awards',
            field=models.ManyToManyField(blank=True, null=True, to='base.award'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='certificates',
            field=models.ManyToManyField(blank=True, null=True, to='base.certificate'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='research_papers',
            field=models.ManyToManyField(blank=True, null=True, to='base.researchpaper'),
        ),
    ]
