# Generated by Django 5.2.5 on 2025-09-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_achievement_awards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='base.course'),
        ),
    ]
