# Generated by Django 5.2.5 on 2025-09-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_achievement_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='educations',
            field=models.ManyToManyField(blank=True, null=True, to='base.education'),
        ),
        migrations.AlterField(
            model_name='about',
            name='hard_skills',
            field=models.ManyToManyField(blank=True, null=True, to='base.hardskill'),
        ),
        migrations.AlterField(
            model_name='about',
            name='soft_skills',
            field=models.ManyToManyField(blank=True, null=True, to='base.softskill'),
        ),
        migrations.AlterField(
            model_name='about',
            name='work_experiences',
            field=models.ManyToManyField(blank=True, null=True, to='base.workexperience'),
        ),
        migrations.AlterField(
            model_name='basicconfiguration',
            name='github_link',
            field=models.CharField(blank=True, help_text='The link must be started with "http:// or https://"', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='basicconfiguration',
            name='instagram_link',
            field=models.CharField(blank=True, help_text='The link must be started with "http:// or https://"', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='basicconfiguration',
            name='linkedin_link',
            field=models.CharField(blank=True, help_text='The link must be started with "http:// or https://"', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='basicconfiguration',
            name='upwork_link',
            field=models.CharField(blank=True, help_text='The link must be started with "http:// or https://"', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='basicconfiguration',
            name='youtube_link',
            field=models.CharField(blank=True, help_text='The link must be started with "http:// or https://"', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_link',
            field=models.CharField(blank=True, help_text='The link must be started with "http:// or https://"', max_length=1000, null=True),
        ),
    ]
