# Generated by Django 5.2.5 on 2025-09-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_about_educations_alter_about_hard_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicconfiguration',
            name='your_number_of_research_papers',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
